name: Test Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Yarn install
        run: yarn install
      - name: Run the tests
        run: yarn test --coverage
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
